"""GeneratedContent database model.

Stores AI-generated content like social posts, articles, donor letters, etc.
"""

import enum
from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base

if TYPE_CHECKING:
    from app.models.ai_task import AITask


class ContentType(str, enum.Enum):
    """Content types that can be generated."""
    
    SOCIAL_POST = "social_post"
    ARTICLE = "article"
    STORY = "story"
    DONOR_LETTER = "donor_letter"
    NEWSLETTER = "newsletter"
    PRAYER_REQUEST = "prayer_request"
    CAMPAIGN_COPY = "campaign_copy"


class GeneratedContent(Base):
    """Generated Content model.
    
    Stores content generated by AI including social posts, articles,
    stories, donor communications, and other content types.
    
    Attributes:
        id: Unique content identifier (UUID)
        task_id: Reference to the AI task that generated this content
        content_type: Type of content (social_post, article, etc.)
        title: Content title (optional)
        body: Main content body (required)
        language: Content language code (en, es, fr, pt)
        platform: Target platform for social posts (facebook, instagram, etc.)
        content_metadata: Additional data (hashtags, mentions, image URLs, etc.)
        quality_score: AI confidence/quality score
        published: Whether content has been published
        published_at: Publication timestamp
        external_id: ID in external system (Content/Social Media Service)
        created_at: Creation timestamp (inherited)
        updated_at: Last update timestamp (inherited)
    """
    
    __tablename__ = "generated_content"
    
    # Override id to use UUID
    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        index=True,
    )
    
    # Foreign key to AI task
    task_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("ai_tasks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    
    # Content information
    content_type: Mapped[ContentType] = mapped_column(
        Enum(ContentType),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=True)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Language and platform
    language: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        default="en",
        index=True,
    )
    platform: Mapped[str] = mapped_column(
        String(50),
        nullable=True,
        index=True,
    )
    
    # Content metadata and quality
    content_metadata: Mapped[dict] = mapped_column(JSONB, nullable=True)
    quality_score: Mapped[float] = mapped_column(Float, nullable=True)
    
    # Publication status
    published: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    published_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    
    # External reference
    external_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        nullable=True,
        index=True,
    )
    
    # Relationships
    task: Mapped["AITask"] = relationship(
        "AITask",
        back_populates="generated_content",
    )
    
    def __repr__(self) -> str:
        return (
            f"<GeneratedContent(id={self.id}, type='{self.content_type.value}', "
            f"language='{self.language}', published={self.published})>"
        )
